[package]
name = "universe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
chrono = "0.4.45"
clap = { version = "4.6.4", features = ["derive"] }
dotenv = "0.15.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "chrono", "sqlite"] }
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
