# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

on:
    pull_request:
        branches:
            - main
env:
  CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup dependencies
              uses: awalsh128/cache-apt-pkgs-action@v1
              with:
                packages: ffmpeg libvips libvips-tools
            - name: Cache
              uses: Swatinem/rust-cache@v2.9.2
            - name: Test
              run: cargo test
